### PR TITLE
Pongo post deploy bug fixes

### LINKED ISSUE #698: Add data explanation dialog on Impact page
Add a button or link on impact page "Explanation of Data";

The dialog should say (and we can update the text as needed):

Data shown in the impact graphs comes from two sources:

  1.  Data collected on the platform from community members who have taken actions;
  2. Data entered by Community Admins for reported actions from State or Partner databases, or from previous community programs.

On the Community impact totals (donut graphs):
1. The Actions Completed graph shows the sum of self reported and state/partner data. In some cases, there may be double counting
2. The Households Engaged is an estimate. Communities sum up self reported households, plus the number of actions completed in the category with the largest number of state/partner values, and added community engagement efforts (plus community specific campaign efforts)
3. The Caron Reduction graph (if shown) shows the estimated reduction for actions taken on the platform, which currently use Massachusetts averages for those actions.  It may also include estimated carbon reduction from reported State/Partner data or previous programs, if that is provided by the Community Admin.

### PR DESCRIPTION
**Pull request by frimpongopoku**
#698 , #683 , #695 , #667 , #696 

Screenshot 2021-10-02 at 15 34 28

### CODE REVIEW

**Review by BradHN1 — APPROVED** [review]
LGTM

File: src/App.js [hunk 1]
```diff
@@ -9,33 +9,32 @@ import LoadingCircle from "./components/Shared/LoadingCircle";
...
-						payload: json.data,
-					})
-        }
-      })
-      .catch((err) => setError(err.message));
-		}
-
-  },[community, dispatch]);
+    if (!community) {
+      apiCall("communities.info", { subdomain: "JCAN" })
```
Comment (BradHN1) [inline src/App.js:18]: Please revert this

**Review by BradHN1 — CHANGES_REQUESTED** [review]
Please revert the change to App.ps. 
Once netlify is the deploy method, changes merged to Dev may deploy automatically, so be careful not to commit test code

**Review by BradHN1 — APPROVED** [review]
I made the small change to approve this PR.
